### PR TITLE
feature(autoload json): Autoload headless json definitions

### PR DESCRIPTION
**Pull request by florianPat**
Hi @lochmueller,
I justed added an autoload feature for the json response for smart objects which create a typoscript configuration for the headless extension automatically based on the content object models defined!
I need to add tests and look at it again, but already wanted to share it, as it might be useful for us?

Best regards,
Flo

### CODE REVIEW

**Comment by lochmueller** [comment]
Hey @florianPat 
Nice work and very useful. You change the Mapper Interface, so this will be a fresh minor/major release. Very cool feature for EXT:headless. If I should merge first stuff, just send me a note...
Regards,
Tim

**Comment by florianPat** [comment]
Hey @lochmueller,
I tested the changes and also added rector and phpstan and looked through the changes one by one (phpstan is on the todolist, through...). I hope I didn`t miss anything.

Thanks for your feedback,
Flo

**Comment by lochmueller** [comment]
Hey @florianPat 
Thanks... great contribution. Next time, try to split the "PHPstand, CS Fixer"-stuff from new features. It is much easier to review and understand. Merge is done... 👍 
Regards,
Tim

**Comment by florianPat** [comment]
Got it, will do that!
Thanks a lot!

**Pull request merged**
