### PR TITLE
added priority annotation handling for slots

### PR DESCRIPTION
**Pull request by monsieurbenny**
a possible solution for #55

### CODE REVIEW

**Comment by orangehive** [comment]
Same Priorities should not override each other. You could add a random postfix to the priority bevor adding it to the array.

**Comment by lochmueller** [comment]
Hey @monsieurbenny 

thanks for the pull request. Please take care, that two slots with the same prio do not overwrite itself. The current patch remove nearly all current slot registrations (because all registrations do not use the @priority at the moment).

Regards,
Tim

**Comment by monsieurbenny** [comment]
You both were so right - i am not exactly shure where my mind has been ;) - sorry for that. I have committed a fixed version. Equal priorities are not overwritten anymore and slots with no priority set are handled with a priority 0. Please have look...

**Comment by lochmueller** [comment]
Great... please ignore Travis. I will check this later.

**Comment by orangehive** [comment]
There is still the possibility that the code without priorty is now in direrent order than before. Since you don't know what hex value you are getting. I don't know if it matters, but this could break already running code.

**Comment by lochmueller** [comment]
Hey @orangehive ,

thanks for the hint, we will refix this shortly: https://github.com/lochmueller/autoloader/issues/57

Regards,
Tim

**Pull request merged**
